defaults:
  - dataset: cifar10
  - model: resnet50_scratch
  - optimizer: adam

seed: 42
device: cuda

data:
  img_size: 224
  batch_size: 64
  num_workers: 4

  val_size: 5000
  stratified_split: true

  train_fraction: 1.0
  stratified_fraction: true

  normalize:
    imagenet:
      mean: [0.485, 0.456, 0.406]
      std:  [0.229, 0.224, 0.225]
    cifar10:
      mean: [0.4914, 0.4822, 0.4465]
      std:  [0.2470, 0.2435, 0.2616]
    cifar100:
      mean: [0.5071, 0.4867, 0.4408]
      std:  [0.2675, 0.2565, 0.2761]

train:
  epochs: 20
  warmup_epochs: 3
  loss_function: "CrossEntropyLoss"
  amp: true

out:
  dir: outputs
  results_csv: results_scale.csv

wandb:
  enable: true
  project: cv-study-e1
  entity: null
  name: null
  group: null
  tags: ["cifar10", "scale"]
  mode: online
  save_code: true