hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - model: bert

seed: 42
device: cuda

dataset:
  name: stanfordnlp/imdb
  batch_size: 32
  val_size: 0.1
  test_size: 0.1
  max_length: 128
  num_labels: 2

optimizer:
  name: adam
  lr: 5e-5
  betas: [0.9, 0.999]
  eps: 1e-6
  weight_decay: 0.01

train:
  epochs: 3

wandb:
  enable: true
  project: nlp-study
  entity: null
  mode: online
  save_code: true
